goober

diff --git a/meow-craft b/meow-craft
--- a/meow-craft
+++ b/meow-craft
@@ -1,4 +1,6 @@
 #!/usr/bin/bash
+set -e
+
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 CYAN='\033[0;36m'
@@ -10,7 +12,7 @@ hint()
     echo -e "${CYAN}${BOLD}Hint: ${NC}$1"
 }
 
-war()
+warn()
 {
     echo -e "${GREEN}${BOLD}Warning: ${NC}$1"
 }
@@ -42,6 +44,13 @@ ${CYAN}${BOLD}  PACKAGE    ${NC}The name of the package to build
 
 ${GREEN}${BOLD}Options:
 ${CYAN}${BOLD}  -i         ${NC}Drop into an interactive shell"
+}
+
+stripall() {
+    for dir in ./usr/lib ./usr/bin ./usr/sbin ./usr/libexec; do
+        [[ -d "$dir" ]] || continue
+        find "$dir" -type f \( -name '*.so*' ! -name '*dbg' -o -name '*.a' \) -exec strip --strip-debug {} +
+    done
 }
 
 build()
@@ -76,10 +85,34 @@ build()
 
     mkdir -p /tmp/meow-craft/sources
     wget -nc -q --show-progress -P /tmp/meow-craft/sources "$SOURCE" || die "Failed to download source from \`$SOURCE\`"
-    SOURCE_FILENAME="/tmp/meow-craft/sources/$(basename "$SOURCE")"
-    SOURCE_DIR="/tmp/meow-craft/sources/$(tar -tf "$SOURCE_FILENAME" | head -n 1)"
+    SOURCE_PATH="/tmp/meow-craft/sources/$(basename "$SOURCE")"
+    SOURCE_DIR="/tmp/meow-craft/sources/$(tar -tf "$SOURCE_PATH" | head -n 1)"
     rm -rf "$SOURCE_DIR"
-    tar -C /tmp/meow-craft/sources -xf "$SOURCE_FILENAME" || die "Failed to extract source archive"
+    tar -C /tmp/meow-craft/sources -xf "$SOURCE_PATH" || die "Failed to extract source archive"
+    export DESTDIR="/tmp/meow-craft/builds/$NAME-$VERSION-$RELEASE"
+    rm -rf $DESTDIR
+    mkdir -p $DESTDIR
+    if [[ $INTERACTIVE -eq 1 ]]; then
+        echo -e "${GREEN}${BOLD}Info: ${NC}Dropping into interactive shell. Exit to continue the build. (exit 1 to abort)"
+        bash -i
+    else
+        bash -c "set -e; source \"$RECIPE/recipe\"; cd \"$SOURCE_DIR\"; build" || die "Build failed"
+    fi
+    for i in {pre,post}-{install,remove}; do
+        cp $RECIPE/$i $DESTDIR 2>/dev/null || true
+    done
+    cd $DESTDIR
+    stripall
+    rm -f $DESTDIR.mz
+    meow-zip create $DESTDIR.mz \
+        --name $NAME \
+        --version $VERSION \
+        --release $RELEASE \
+        --license "$LICENSE" \
+        --depends "$DEPENDS" \
+        --packager "$PACKAGER"
+    meow-zip list $DESTDIR.mz
+    echo -e "${GREEN}${BOLD}Success: ${NC}Package built at \`$DESTDIR.mz\`"
 }
 
 case "$1" in
